version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /opt/stoov

permissions:
  - object: /opt/stoov/scripts
    pattern: "**"
    mode: 755
    owner: root
    group: root

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/clean.sh
      runas: root
  AfterInstall:
    - location: scripts/build_and_copy.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/health.sh
      timeout: 180
      runas: root
