CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    sub VARCHAR(64) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    profile_image_url VARCHAR(2048),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_sub UNIQUE (sub)
);

CREATE TABLE user_agreement (
    user_agreement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    user_email VARCHAR(254) NOT NULL,
    user_nickname VARCHAR(30)  NOT NULL,
    agreed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_agreement_user UNIQUE (user_id)
);

CREATE TABLE place (
    place_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,        -- 장소명
    address VARCHAR(200) NOT NULL,     -- 도로명 주소
    district VARCHAR(50) NOT NULL,     -- 구/행정구역
    lat NUMERIC(9,6) NOT NULL,         -- 위도
    lng NUMERIC(9,6) NOT NULL,         -- 경도
    location GEOGRAPHY(Point, 4326),   -- 좌표
    type VARCHAR(20) NOT NULL,         -- 장소 유형 (Enum: RIVER_PARK, SQUARE, STREET)
    contact VARCHAR(150),              -- 연락처
    reservation_url VARCHAR(2048),     -- 예약 페이지 URL
    operation_time VARCHAR(100),       -- 운영시간
    available_days VARCHAR(50),        -- 사용 가능 요일
    fee VARCHAR(10),                   -- 이용요금 (Enum: FREE, PAID, UNKNOWN)
    max_performers VARCHAR(15),        -- 최대 인원 (Enum: LIMITED, UNLIMITED, UNKNOWN)
    how_to_apply VARCHAR(260),         -- 신청방법
    electricity_available BOOLEAN,     -- 전기 사용 가능 여부
    thumbnail_url VARCHAR(2048),       -- 썸네일 URL
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorite (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    place_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id)
        REFERENCES users(user_id)
            ON DELETE CASCADE,          -- 유저 삭제 시 연관 즐겨찾기 자동 삭제
            CONSTRAINT fk_favorite_place FOREIGN KEY (place_id)
        REFERENCES place(place_id)
            ON DELETE CASCADE,          -- 장소 삭제 시 연관 즐겨찾기 자동 삭제
            CONSTRAINT uq_favorite_user_place UNIQUE (user_id, place_id)
);

CREATE TABLE review (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    place_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE SET NULL,        -- 유저 삭제 후에도 리뷰는 보존
    CONSTRAINT fk_review_place FOREIGN KEY (place_id)
        REFERENCES place(place_id)
        ON DELETE CASCADE          -- 장소 삭제 시 연관 리뷰 자동 삭제
);

CREATE INDEX idx_user_agreement_email
    ON user_agreement (user_email);

CREATE INDEX idx_user_agreement_nickname
    ON user_agreement (user_nickname);