CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    sub VARCHAR(64) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    profile_image_url VARCHAR(2048),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_sub UNIQUE (sub)
);

CREATE TABLE user_agreement (
    user_agreement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    user_email VARCHAR(254) NOT NULL,
    user_nickname VARCHAR(30)  NOT NULL,
    agreed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_agreement_user UNIQUE (user_id)
);

CREATE INDEX idx_user_agreement_email
    ON user_agreement (user_email);

CREATE INDEX idx_user_agreement_nickname
    ON user_agreement (user_nickname);